# Generated by Django 3.2.4 on 2021-06-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='user_type',
            field=models.CharField(choices=[('patient', 'pt'), ('doctor', 'doctor'), ('examiner', 'examiner')], max_length=64),
        ),
    ]
