# Generated by Django 3.2.4 on 2021-06-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_portaluser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='user_type',
            field=models.CharField(choices=[('patient', 'patient'), ('doctor', 'doctor'), ('examiner', 'examiner')], max_length=64),
        ),
    ]
