# Generated by Django 3.2.4 on 2021-06-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_portaluser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
