# Generated by Django 3.2.4 on 2021-06-21 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_portaluser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='DoctorSpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_creater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('license_file', models.FileField(upload_to='media/images/doctor/liscence/')),
                ('is_verified', models.BooleanField(default=False)),
                ('degree', models.CharField(max_length=120)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('speciality', models.ManyToManyField(related_name='doc_speciality', to='users.DoctorSpeciality')),
                ('user', models.ForeignKey(on_delete=django.db.models.fields.CharField, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
