# Generated by Django 3.2.4 on 2021-06-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_doctor_license_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
